### ISSUE TITLE
Queue Cleaner Doesn't See Downloads With Warnings.

### ISSUE THREAD

**Issue by EthicalObligation** [RandomNinjaAtk/docker-sonarr-extended#25]

**Comment by EthicalObligation** [comment]
#24

**Comment by RandomNinjaAtk** [comment]
What is a use-case where you only have an item with a warning only?

The current use-case is to only clear completed downloads that fail to import automatically because they have a warning status. I feel like removing everything with a warning status is possibly taking it too far and would have undesirable results.

**Comment by EthicalObligation** [comment]
I will definitely check it out for stability. Thank you for bringing that to my attention.

**Comment by RandomNinjaAtk** [comment]
This script was moved to a new repo and made as a universal script.
